### ISSUE TITLE
Error: Too few arguments to function RCView::span()

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_webservices#10]
Andres Vasquez reports:

```
REDCap crashed due to an unexpected PHP fatal error!
Error message: Uncaught ArgumentCountError: Too few arguments to function RCView::span(), 1 passed in 
/nfs/c12/h05/mnt/222648/domains/xxx/html/redcap/modules/redcap_webservices_v1.0.3/plugins/webservices_list.php on line 36 
and at least 2 expected in /nfs/c12/h05/mnt/222648/domains/citei.org/html/redcap/redcap_v8.11.7/Classes/RCView.php:98 Stack trace: 
#0 /nfs/c12/h05/mnt/222648/domains/xxx/html/redcap/modules/redcap_webservices_v1.0.3/plugins/webservices_list.php(36): RCView::span(Array) 
#1 /nfs/c12/h05/mnt/222648/domains/xxx/html/redcap/redcap_v8.11.7/ExternalModules/index.php(102): require_once('/nfs/c12/h05/mn...') 
#2 {main} thrown
File: /nfs/c12/h05/mnt/222648/domains/citei.org/html/redcap/redcap_v8.11.7/Classes/RCView.php
Line: 98
```

This is probably related to his recent PHP upgrade. See https://www.php.net/manual/en/migration71.incompatible.php

**Comment by marlycormar** [comment]
Fixed by issue #11.
